<script type="text/javascript" src="../bower_components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="../bower_components/slick.js/slick/slick.min.js"></script>
<!--<script type="text/javascript" src="../crappy_bower_component/fine-uploader/fine-uploader.min.js"></script>-->
<script type="text/javascript" src="../bower_components/fine-uploader/_build/fine-uploader.min.js"></script>
<script type="text/javascript" src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../bower_components/bootstrap-rating/bootstrap-rating.min.js"></script>
<script type="text/javascript" src="../bower_components/jquery.countdown/dist/jquery.countdown.min.js"></script>
<script type="text/javascript" src="./scripts/main.js"></script>
<?php if($app->voteOpened): ?>
<script type="text/javascript" src="./scripts/ratings.js"></script>
<?php endif; ?>
<?php if($app->submitOpened): ?>
<script type="text/javascript" src="./scripts/upload.js"></script>
<?php endif; ?>
